"""
Module for exporting to standardized CSV format - Simplified version for rapid delivery
"""
import pandas as pd
from typing import Dict, List, Optional, Any
from datetime import datetime
import logging
import numpy as np

class CSVExporter:
    """Exports data to CSV with biomedical standards - Accelerated version"""
    
    def __init__(self, separator: str = '\t', include_header: bool = True):
        self.separator = separator
        self.include_header = include_header
        self.logger = logging.getLogger('CSVExporter')
    
    def export_standard_csv(self, data: pd.DataFrame, 
                           output_path: str,
                           metadata: Optional[Dict[str, Any]] = None, **kwargs) -> bool:
        """
        Exports data to CSV with metadata
        
        Args:
            data: Data to export
            output_path: Output path
            metadata: Metadata to include
        
        Returns:
            True if success, False otherwise
        """
        self.logger.info(f"CSV export to {output_path}")
        
        try:
            # Create metadata lines
            metadata_rows = []
            if metadata:
                metadata_rows.append(f"# Metadata: {metadata}")
            
            metadata_rows.extend([
                f"# Export date: {datetime.now().isoformat()}",
                f"# Dataset: {len(data)} samples, {len(data.columns)} features",
                f"# Generated by: Multi-Omics Pipeline v1.0"
            ])
            
            # Write metadata in header
            with open(output_path, 'w', encoding='utf-8') as f:
                for row in metadata_rows:
                    f.write(row + '\n')
            
            # Add data
            data.to_csv(output_path, 
                       sep=self.separator,
                       header=self.include_header,
                       index=False,
                       mode='a',  # Append mode
                       encoding='utf-8')
            
            self.logger.info(f"[OK] CSV export complete: {output_path}")
            return True
            
        except Exception as e:
            self.logger.error(f"[Error] Error during CSV export: {e}")
            return False
    
    def export_with_data_dictionary(self, data: pd.DataFrame, 
                                   output_path: str,
                                   data_dictionary: Optional[Dict[str, str]] = None) -> bool:
        """
        Exports with a data dictionary
        
        Args:
            data: Data to export
            output_path: Output path
            data_dictionary: Column descriptions
        
        Returns:
            True if success, False otherwise
        """
        self.logger.info(f"CSV export with dictionary to {output_path}")
        
        try:
            # Create data dictionary if not provided
            if data_dictionary is None:
                data_dictionary = self._generate_data_dictionary(data)
            
            # Create description lines
            description_rows = []
            description_rows.append("# Data Dictionary:")
            description_rows.append("# Column_Name\tDescription\tData_Type\tExample")
            
            for col in data.columns:
                description = data_dictionary.get(col, f"{col} - Description not provided")
                dtype = str(data[col].dtype)
                example = str(data[col].dropna().iloc[0]) if not data[col].dropna().empty else "N/A"
                
                description_rows.append(f"# {col}\t{description}\t{dtype}\t{example}")
            
            # Write descriptions
            with open(output_path, 'w', encoding='utf-8') as f:
                for row in description_rows:
                    f.write(row + '\n')
                
                # Empty line before data
                f.write('\n')
            
            # Add data
            data.to_csv(output_path, 
                       sep=self.separator,
                       header=self.include_header,
                       index=False,
                       mode='a',
                       encoding='utf-8')
            
            self.logger.info(f"[OK] CSV export with dictionary complete: {output_path}")
            return True
            
        except Exception as e:
            self.logger.error(f"[Error] Error during CSV export with dictionary: {e}")
            return False
    
    def export_split_by_type(self, data: pd.DataFrame, 
                           output_dir: str,
                           type_column: str = 'data_type') -> bool:
        """
        Exports data separated by type into different files
        
        Args:
            data: Data to export
            output_dir: Output directory
            type_column: Column for separating data
        
        Returns:
            True if success, False otherwise
        """
        self.logger.info(f"Export separated by type to {output_dir}")
        
        try:
            import os
            os.makedirs(output_dir, exist_ok=True)
            
            if type_column not in data.columns:
                self.logger.error(f"Column {type_column} not found")
                return False
            
            # Group by type and export
            exported_count = 0
            for data_type, group in data.groupby(type_column):
                output_path = os.path.join(output_dir, f"{data_type}_data.csv")
                
                success = self.export_standard_csv(group, output_path, {
                    'data_type': data_type,
                    'n_samples': len(group)
                })
                
                if success:
                    exported_count += 1
            
            self.logger.info(f"[OK] Separated export complete: {exported_count} files created")
            return True
            
        except Exception as e:
            self.logger.error(f"[Error] Error during separated export: {e}")
            return False
    
    def export_for_bioconductor(self, data: pd.DataFrame, 
                               output_path: str,
                               feature_column: str = 'gene_id') -> bool:
        """
        Exports to Bioconductor/R compatible format
        
        Args:
            data: Data to export
            output_path: Output path
            feature_column: Feature (gene) column
        
        Returns:
            True if success, False otherwise
        """
        self.logger.info(f"Bioconductor format export to {output_path}")
        
        try:
            if feature_column not in data.columns:
                self.logger.error(f"Feature column {feature_column} not found")
                return False
            
            # Set features as index for matrix format
            bioconductor_data = data.set_index(feature_column)
            
            # Keep only numeric columns
            numeric_cols = bioconductor_data.select_dtypes(include=[np.number]).columns
            bioconductor_data = bioconductor_data[numeric_cols]
            
            # Export with dot as decimal separator for R compatibility
            bioconductor_data.to_csv(output_path, 
                                   sep=self.separator,
                                   header=True,
                                   index=True,
                                   decimal='.')  # Dot for R
            
            self.logger.info(f"[OK] Bioconductor export complete: {output_path}")
            return True
            
        except Exception as e:
            self.logger.error(f"[Error] Error during Bioconductor export: {e}")
            return False
    
    def _generate_data_dictionary(self, data: pd.DataFrame) -> Dict[str, str]:
        """Automatically generates a data dictionary"""
        dictionary = {}
        
        for col in data.columns:
            dtype = str(data[col].dtype)
            
            # Generate a description based on name and type
            if 'id' in col.lower() or 'patient' in col.lower():
                description = f"Unique identifier of the sample ({col})"
            elif any(gene_term in col.lower() for gene_term in ['gene', 'tp53', 'brca', 'egfr']):
                description = f"Expression of gene {col} (normalized values)"
            elif any(clinical_term in col.lower() for clinical_term in ['age', 'stage', 'grade', 'survival']):
                description = f"Clinical variable: {col}"
            else:
                description = f"Variable {col} of type {dtype}"
            
            dictionary[col] = description
        
        return dictionary
    
    def export_with_validation(self, data: pd.DataFrame, 
                               output_path: str,
                               validation_rules: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Exports with data validation
        
        Args:
            data: Data to export
            output_path: Output path
            validation_rules: Validation rules
        
        Returns:
            Validation and export report
        """
        self.logger.info(f"Export with validation to {output_path}")
        
        validation_report = {
            'validation_successful': True,
            'warnings': [],
            'errors': [],
            'export_successful': False
        }
        
        try:
            # Basic validation
            if data.empty:
                validation_report['errors'].append("Empty dataset")
                validation_report['validation_successful'] = False
            
            if data.isnull().all().all():
                validation_report['errors'].append("All values are missing")
                validation_report['validation_successful'] = False
            
            # Check custom validation rules
            if validation_rules:
                for col, rule in validation_rules.items():
                    if col in data.columns:
                        if 'min' in rule and data[col].min() < rule['min']:
                            validation_report['warnings'].append(f"{col}: values below minimum")
                        
                        if 'max' in rule and data[col].max() > rule['max']:
                            validation_report['warnings'].append(f"{col}: values above maximum")
            
            # Export if validation OK
            if validation_report['validation_successful']:
                export_success = self.export_standard_csv(data, output_path)
                validation_report['export_successful'] = export_success
            
            return validation_report
            
        except Exception as e:
            validation_report['errors'].append(f"Error during validation: {e}")
            validation_report['validation_successful'] = False
            return validation_report

# Quick tests
if __name__ == "__main__":
    import numpy as np
    # Create test data
    test_data = pd.DataFrame({
        'patient_id': ['P001', 'P002', 'P003'],
        'TP53': [1.5, 2.3, 0.8],
        'BRCA1': [2.1, 1.9, 3.2],
        'age': [45, 50, 55],
        'stage': ['I', 'II', 'I']
    })
    
    print("=== CSV EXPORTER TEST ===")
    print("Original data:")
    print(test_data)
    
    # Test standard export
    exporter = CSVExporter(separator='\t')
    success = exporter.export_standard_csv(test_data, 'test_export.csv', {
        'source': 'multi_omics_pipeline',
        'version': '1.0'
    })
    
    print(f"\nStandard export: {'[OK] Success' if success else '[Error] Failure'}")
    
    # Test export with dictionary
    success_dict = exporter.export_with_data_dictionary(test_data, 'test_with_dict.csv')
    print(f"Export with dictionary: {'[OK] Success' if success_dict else '[Error] Failure'}")
    
    # Read and verify exported file
    try:
        with open('test_export.csv', 'r') as f:
            content = f.read()
        
        print(f"\nCSV file preview:")
        print(content[:200] + "..." if len(content) > 200 else content)
        
    except Exception as e:
        print(f"Error during file reading: {e}")